name: 'Linux Desktop: UI mobile'
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    uses: ./.github/workflows/desktop-build.yml
    with:
      platform: linux
      mobile-ui: true
